WebUI/Areas/Admin/Controllers/BrandController.cs
using Entity.Concrete.DTOs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Services.Abstract;
using Shared.Utilities.Results.ComplexTypes;
using Shared.Utilities.Results.Concrete;

namespace WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin,Editor")]
    public class BrandController : Controller
    {
        private readonly IBrandService _brandService;

        public BrandController(IBrandService brandService)
        {
            _brandService = brandService;
        }

        public async Task<IActionResult> List()
        {
            var brands = await _brandService.GetAllByNonDeleted();
            return View(brands.Data);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return PartialView("_BrandAddPartial");
        }

        [HttpPost]
        public async Task<IActionResult> Add(BrandAddDto brandAddDto)
        {
            if (ModelState.IsValid)
            {
                var result = await _brandService.Add(brandAddDto);
                return Json(result);
            }
            var errorMessage = string.Join(" | ", ModelState.Values
                    .SelectMany(v => v.Errors)
                    .Select(e => e.ErrorMessage));

            string errorResultMessage = "Ekleme sırasında hata ile karşılaşıldı.";

            foreach (var errMsg in errorMessage)
            {
                errorResultMessage += errMsg.ToString();
            }

            Result errorResult = new(ResultStatus.Error, errorResultMessage);

            return Json(errorResult);
        }

        [HttpPost]
        public async Task<JsonResult> Remove(int brandId)
        {
            var result = await _brandService.Delete(brandId);       
            return Json(result);
        }

        [HttpGet]
        public async Task<IActionResult> Update(int brandId)
        {
            var result = await _brandService.GetUpdateDto(brandId);
            return PartialView("_BrandUpdatePartial",result.Data);
        }

        [HttpPost]
        public async Task<IActionResult> Update(BrandUpdateDto brandUpdateDto)
        {
            if (ModelState.IsValid)
            {
                var result = await _brandService.Update(brandUpdateDto);
                return Json(result);
            }
            var errorMessage = string.Join(" | ", ModelState.Values
                    .SelectMany(v => v.Errors)
                    .Select(e => e.ErrorMessage));

            string errorResultMessage = "Güncelleme sırasında hata ile karşılaşıldı.";

            foreach (var errMsg in errorMessage)
            {
                errorResultMessage += errMsg.ToString();
            }

            Result errorResult = new(ResultStatus.Error, errorResultMessage);

            return Json(errorResult);
        }
    }
}

WebUI/Areas/Admin/Controllers/CarController.cs
using AutoMapper;
using Entity.ComplexTypes;
using Entity.Concrete.DTOs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Services.Abstract;
using Shared.Utilities.Results.ComplexTypes;
using Shared.Utilities.Results.Concrete;
using WebUI.Areas.Admin.Models;

namespace WebUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin,Editor")]
    public class CarController : Controller
    {
        private readonly ICarService _carService;
        private readonly ICarModelService _carModelService;
        private readonly IBrandService _brandService;
        private readonly IColorService _colorService;
        private readonly INotificationService _notificationService;
        private readonly IMapper _mapper;

        public CarController(INotificationService notificationService, ICarService carService, ICarModelService carModelService, IBrandService brandService, IColorService colorService
            ,IMapper mapper)
        {
            _carService = carService;
            _carModelService = carModelService;
            _brandService = brandService;
            _colorService = colorService;
            _mapper = mapper;
            _notificationService = notificationService;
        }

        public async Task<IActionResult> List()
        {
            var result = await _carService.GetAllByNonDeleted();
            return View(result.Data);
        }

        [HttpGet]
        public async Task<JsonResult> GetCarModelsByBrand(int brandId)
        {
            var result = await _carModelService.GetAllByNonDeletedByBrandId(brandId);
            if (result?.Data?.CarModels.Count() > 0)
            {
                return Json(result?.Data?.CarModels);
            }
            return Json(new { message = "Seçtiğiniz markaya ait model yok", isError = true });
        }

        [HttpGet]
        public async Task<IActionResult> Add()
        {
            await SelectListState();

            return PartialView("_CarAddPartial");
        }

        private async Task SelectListState()
        {
            var brandResult = await _brandService.GetAllByNonDeleted();
            var brandSelectList = brandResult?.Data?.Brands?.Select(b => new SelectListItem()
            {
                Value = b.ID.ToString(),
                Text = b.Name
            }).ToList();

            var colorResult = await _colorService.GetAllByNonDeleted();
            var colorSelectList = colorResult?.Data?.Colors?.Select(b => new SelectListItem()
            {
                Value = b.ID.ToString(),
                Text = b.Name
            }).ToList();

            var transmissionType = from TransmissionType t in Enum.GetValues(typeof(TransmissionType))
                                   select new { Value = (int)t, Text = t.ToString() };

            var transmissionTypeSelectList = transmissionType.Select(t => new SelectListItem()
            {
                Value = t.Value.ToString(),
                Text = t.Text
            }).ToList();

            var fuelType = from FuelType f in Enum.GetValues(typeof(FuelType))
                           select new { Value = (int)f, Text = f.ToString() };

            var fuelTypeSelectList = fuelType.Select(f => new SelectListItem()
            {
                Value = f.Value.ToString(),
                Text = f.Text
            }).ToList();

            var vehicleType = from VehicleType v in Enum.GetValues(typeof(VehicleType))
                              select new { Value = (int)v, Text = v.ToString() };

            var vehicleTypeSelectList = vehicleType.Select(v => new SelectListItem()
            {
                Value = v.Value.ToString(),
                Text = v.Text
            }).ToList();           

            ViewBag.PageState = new DashboardModel
            {
                SelectListItemForBrands = brandSelectList,
                SelectListItemForColors = colorSelectList,
                SelectListItemForTransmissionType = transmissionTypeSelectList,
                SelectListItemForFuelType = fuelTypeSelectList,
                SelectListItemForVehicleType = vehicleTypeSelectList
            };
        }

        [HttpPost]
        public async Task<IActionResult> Add(CarAddDto carAddDto)
        {
            if (ModelState.IsValid)
            {
                var result = await _carService.Add(carAddDto);
                //Notification
                var carListDto = await _carService.GetAllByNonDeleted();
                var car = carListDto?.Data?.Cars?.OrderByDescending(c => c.CreatedDate).First();
                var notification = new NotificationAddDto
                {
                    Message = $"{car.CarModel.Brand.Name} {car.CarModel.Name} adlı araç eklenmiştir."
                };
                await _notificationService.Add(notification);
                return Json(result);
            }
            var errorMessage = string.Join(" | ", ModelState.Values
                    .SelectMany(v => v.Errors)
                    .Select(e => e.ErrorMessage));

            string errorResultMessage = "Ekleme sırasında hata ile karşılaşıldı.";

            foreach (var errMsg in errorMessage)
            {
                errorResultMessage += errMsg.ToString();
            }

            Result errorResult = new(ResultStatus.Error, errorResultMessage);

            return Json(errorResult);
        }

        [HttpPost]
        public async Task<IActionResult> Remove(int carId)
        {
            if (carId != 0)
            {
                var result = await _carService.Delete(carId);
                if (result.ResultStatus == ResultStatus.Success)
                {
                    return Json(new { message = result.Message, resultStatus = true }); 
                }
                else
                {
                    return Json(new { message = result.Message });
                }
            }
            return Json(new { message = "id 0 olamaz" });
        }

        [HttpGet]
        public async Task<IActionResult> Update(int carId)
        {
            await SelectListState();
            var result = await _carService.Get(carId);


            var carModelResult = await _carModelService.GetAllByNonDeletedByBrandId(result.Data.Car.CarModel.BrandId);
            var carModelSelectList = carModelResult?.Data?.CarModels?.Select(b => new SelectListItem()
            {
                Value = b.ID.ToString(),
                Text = b.Name
            }).ToList();

            ViewBag.CarUpdate = carModelSelectList;

            var carUpdateDto = _mapper.Map<CarUpdateDto>(result.Data.Car);
            return PartialView("_CarUpdatePartial", carUpdateDto);
        }

        [HttpPost]
        public async Task<IActionResult> Update(CarUpdateDto carUpdateDto)
        {
            if (ModelState.IsValid)
            {
                var result = await _carService.Update(carUpdateDto);
                return Json(result);
            }
            var errorMessage = string.Join(" | ", ModelState.Values
                    .SelectMany(v => v.Errors)
                    .Select(e => e.ErrorMessage));

            string errorResultMessage = "Güncelleme sırasında hata ile karşılaşıldı.";

            foreach (var errMsg in errorMessage)
            {
                errorResultMessage += errMsg.ToString();
            }

            Result errorResult = new(ResultStatus.Error, errorResultMessage);

            return Json(errorResult);
        }

    }
}

WebUI/Areas/Admin/Views/Car/List.cshtml
@using Entity.ComplexTypes
@model Entity.Concrete.DTOs.CarListDto

<div id="modal"></div>
<div class="container-fluid">
    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Araçlarımız</h1>
    <p class="mb-4">Aşağıdaki listede şirketimizde olan araçlarımız bulunmaktadır.</p>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">Araç Listesi</h6>
        </div>
        <div class="card-body">
            <button class="btn btn-success mb-3" id="btnAdd">Yeni Bir Araç Ekle</button>
            <div class="table-responsive">
                <table id="carTable" class="table table-bordered" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Resim</th>
                            <th>Marka</th>
                            <th>Model</th>
                            <th>Günlük Ücret</th>
                            <th>Renk</th>
                            <th>Vites Tipi</th>
                            <th>Yakıt Tipi</th>
                            <th>Kasa Tipi</th>
                            <th>Açıklama</th>
                            <th>Mevcut Adet</th>
                            <th>Toplam Adet</th>
                            <th>İşlemler</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model.Cars)
                        {
                            <tr data-id="@item.ID">
                                <td>@item.ID</td>
                                <td>
                                    <div class="spinner-border text-primary img-car-loaded" role="status">
                                        <span class="sr-only">Loading...</span>
                                    </div>
                                    <img class="img-car" src="@item.Image" />
                                </td>
                                <td>@item?.CarModel?.Brand?.Name</td>
                                <td>@item?.CarModel?.Name</td>
                                <td>@item.DailyPrice ₺</td>
                                <td>@item?.Color?.Name</td>
                                <td>
                                    @{
                                        var transmissionType = (TransmissionType)item.TransmissionType;
                                    }
                                    @transmissionType
                                </td>
                                <td>
                                    @{
                                        var fuelType = (FuelType)item.FuelType;
                                    }
                                    @fuelType
                                </td>
                                <td>
                                    @{
                                        var vehicleType = (VehicleType)item.VehicleType;
                                    }
                                    @vehicleType
                                </td>
                                <td>
                                    @item.Description
                                </td>
                                <td>
                                    @item.CurrentCount
                                </td>
                                <td>
                                    @item.TotalCount
                                </td>
                                <td class="d-flex justify-content-around">
                                    <span class="btn btn-sm btn-danger removeCar" id="@item?.ID">Sil</span>
                                    <span class="btn btn-sm btn-warning carUpdate" id="@item?.ID">Güncelle</span>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>


@section scripts{
    <script>
        $(document).ready(function() {
            $('#carTable').DataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Turkish.json"
                }
            });
            //add get for car
            const url = '@Url.Action("Add","Car")';
            const modalDiv = $("#modal");
            $("#btnAdd").click(function() {
                $.get(url).done(function(data) {
                    modalDiv.html(data);
                    modalDiv.find(".modal").show('slow');
                });
            });

            //update get for car
            $(".carUpdate").click(function() {
                const url = '@Url.Action("Update","Car")';
                const modalDiv = $("#modal");
                var Id = $(this).attr('id');
                $.get(url, { carId:Id }).done(function(data) {
                    modalDiv.html(data);
                    modalDiv.find(".modal").show('slow');
                });
            });

            //remove for car
            $(".removeCar").click(function() {
                Swal.fire({
                    title: 'Emin misin?',
                    text: "Silmek istediğine emin misin?",
                    icon: 'warning',
                    showCancelButton: true,
                    confirmButtonColor: '#3085d6',
                    cancelButtonColor: '#d33',
                    confirmButtonText: 'Evet Sil!'
                }).then((result) => {
                    if (result.isConfirmed) {
                        const url = '@Url.Action("Remove","Car")';
                        const Id = $(this).attr('id');
                        $.post(url, { carId: Id }).done(function(data) {
                            var stringifyData = JSON.stringify(data); // "key":"data"
                            var jsonData = jQuery.parseJSON(stringifyData); //jsObject
                            if (jsonData.resultStatus === true) {
                                const tr = $(`[data-id="${Id}"]`);
                                tr.fadeOut(2500);
                                toastr.success(`${jsonData.message}`, 'Başarılı İşlem');
                            }
                            else {
                                toastr.error(`${jsonData.message}`, 'Başarısız İşlem');
                            }
                        });
                    }
                });
            });

            //loading image indicator
            $(".img-car").on('load', function() {
                setTimeout(function() {
                    $(".img-car-loaded").css({ "display": "none" });
                    $(".img-car").css({ "display": "inline" });
                }, 2500);
            });
        });
    </script>
}

WebUI/Areas/Admin/Views/Car/_CarAddPartial.cshtml
@using Entity.Concrete
@using Entity.Concrete.DTOs
@model CarAddDto

@{
    var pageState = ViewBag.PageState as WebUI.Areas.Admin.Models.DashboardModel;
}

<div class="modal">
    <div class="modal-dialog" style="overflow-y: initial !important;">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-primary"><i class="fa-solid fa-circle-plus"></i> Araç Ekle</h5>
                <button type="button" class="close cancel">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" style="height:80vh; overflow-y:auto;">
                <form asp-action="Add" id="form-add">
                    <div class="form-group">
                        <label style="color:black;">Marka</label>
                        <span class="btn btn-success btn-sm float-right" id="addBrand">+</span>
                        <select class="form-control" id="brandSelect" asp-items="@pageState?.SelectListItemForBrands">
                            <option>Marka Seçiniz</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label style="color:black;">Model</label>
                        <select class="form-control" id="carModel" asp-for="CarModelId">
                            <option>Model Seçiniz</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label style="color:black;" asp-for="ModelYear"></label>
                        <input class="form-control" asp-for="ModelYear" type="number" placeholder="Min:2000, Max:2020" min="2000" max="2020">
                    </div>
                    <div class="form-group">
                        <label style="color:black;" asp-for="DailyPrice"></label>
                        <input class="form-control" asp-for="DailyPrice" type="number" placeholder="Günlük Kiralama Ücretini Giriniz..">
                    </div>
                    <div class="form-group">
                        <label style="color:black;">Renk</label>
                        <select class="form-control" asp-for="ColorId" asp-items="@pageState?.SelectListItemForColors">
                            <option>Renk Seçiniz</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label style="color:black;">Vites Tipi</label>
                        <select class="form-control" asp-for="TransmissionType" asp-items="@pageState?.SelectListItemForTransmissionType">
                            <option>Vites Tipi Seçiniz</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label style="color:black;">Yakıt Türü</label>
                        <select class="form-control" asp-for="FuelType" asp-items="@pageState?.SelectListItemForFuelType">
                            <option>Yakıt Türü Seçiniz</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label style="color:black;">Kasa Tipi</label>
                        <select class="form-control" asp-for="VehicleType" asp-items="@pageState?.SelectListItemForVehicleType">
                            <option>Kasa Tipi Seçiniz</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label style="color:black;" asp-for="Image"></label>
                        <input class="form-control" asp-for="Image" type="text" placeholder="Resim url giriniz..">
                    </div>
                    <div class="form-group">
                        <label style="color:black;" asp-for="TotalCount"></label>
                        <input class="form-control" asp-for="TotalCount" type="number" placeholder="Toplam Araç Adedi">
                    </div>
                    <div class="form-group">
                        <label style="color:black;" asp-for="Description"></label>
                        <textarea class="form-control" asp-for="Description" placeholder="Açıklama giriniz.." rows="4"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary cancel">Kapat</button>
                <button type="button" class="btn btn-primary save">Kaydet</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $(".cancel").click(function() {
            $(".modal").hide("slow");
        });
        $("#brandSelect").change(function() {
            $("#carModel option").each(function() {
                $(this).remove();
            });
            var id = $(this).val();
            var url = '@Url.Action("GetCarModelsByBrand","Car")';
            $.get(url, { brandId: id }).done(function(data) {
                var stringifyData = JSON.stringify(data); // "key":"data"
                var jsonData = jQuery.parseJSON(stringifyData); //jsObject
                console.log(jsonData);
                if (jsonData.isError === true) {
                    $("#carModel").append(`<option>${jsonData.message}</option>`);
                }
                else {
                    for (var carModel of jsonData) {
                        $("#carModel").append(`<option value="${carModel.id}">${carModel.name}</option>`);
                    }
                }
            });
        });

        $("#addBrand").click(function() {
            const url = '@Url.Action("Add","Brand")';
            const modalDiv = $("#modal");
            $.get(url).done(function(data) {
                modalDiv.html(data);
                modalDiv.find(".modal").show('slow');
            });
        });

        $(".save").click(function() {
            const form = $("#form-add");
            const actionUrl = form.attr("action");
            const dataToSend = form.serialize();
            $.post(actionUrl, dataToSend).done(function(data) {
                var stringifyData = JSON.stringify(data); // "key":"data"
                var jsonData = jQuery.parseJSON(stringifyData); //jsObject
                if (jsonData.resultStatus == "Success") {
                    Swal.fire({
                        icon: 'success',
                        title: 'Başarıyla Eklendi',
                        text: jsonData.message
                    }).then((result) => {
                        if (result.isConfirmed) {
                            location.reload(true);
                        }
                    });
                } else {
                    Swal.fire({
                        icon: 'error',
                        title: 'Ekleme Başarısız',
                        text: jsonData.message
                    });
                }
            });
        });
    });
</script>

WebUI/Areas/Admin/Views/Car/_CarUpdatePartial.cshtml
@using Entity.Concrete
@using Entity.Concrete.DTOs
@model CarUpdateDto

@{
    var pageState = ViewBag.PageState as WebUI.Areas.Admin.Models.DashboardModel;
    var carUpdate = ViewBag.CarUpdate as List<SelectListItem>;
}

<div class="modal">
    <div class="modal-dialog" style="overflow-y: initial !important;">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title text-primary"><i class="fa-solid fa-pen-to-square"></i> Araç Güncelle</h5>
                <button type="button" class="close cancel">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" style="height:80vh; overflow-y:auto;">
                <form asp-action="Update" id="form-update">
                    <input type="hidden" asp-for="ID"/>
                    <div class="form-group">
                        <label style="color:black;">Marka</label>
                        <span class="btn btn-success btn-sm float-right" id="addBrand">+</span>
                        <select class="form-control" asp-for="CarModel.BrandId" id="brandSelect" asp-items="@pageState?.SelectListItemForBrands">
                            <option>Marka Seçiniz</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label style="color:black;">Model</label>
                        <select class="form-control" id="carModel" asp-for="CarModelId" asp-items="@carUpdate">
                            <option>Model Seçiniz</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label style="color:black;" asp-for="ModelYear"></label>
                        <input class="form-control" asp-for="ModelYear" type="number">
                    </div>
                    <div class="form-group">
                        <label style="color:black;" asp-for="DailyPrice"></label>
                        <input class="form-control" asp-for="DailyPrice" type="number" placeholder="Günlük Kiralama Ücretini Giriniz..">
                    </div>
                    <div class="form-group">
                        <label style="color:black;">Renk</label>
                        <select class="form-control" asp-for="ColorId" asp-items="@pageState?.SelectListItemForColors">
                            <option>Renk Seçiniz</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label style="color:black;">Vites Tipi</label>
                        <select class="form-control" asp-for="TransmissionType" asp-items="@pageState?.SelectListItemForTransmissionType">
                            <option>Vites Tipi Seçiniz</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label style="color:black;">Yakıt Türü</label>
                        <select class="form-control" asp-for="FuelType" asp-items="@pageState?.SelectListItemForFuelType">
                            <option>Yakıt Türü Seçiniz</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label style="color:black;">Kasa Tipi</label>
                        <select class="form-control" asp-for="VehicleType" asp-items="@pageState?.SelectListItemForVehicleType">
                            <option>Kasa Tipi Seçiniz</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label style="color:black;" asp-for="Image"></label>
                        <input class="form-control" asp-for="Image" type="text" placeholder="Resim url giriniz..">
                    </div>
                    <div class="form-group">
                        <label style="color:black;" asp-for="TotalCount"></label>
                        <input class="form-control" asp-for="TotalCount" type="number" placeholder="Toplam Araç Adedi">
                    </div>
                    <div class="form-group">
                        <label style="color:black;" asp-for="Description"></label>
                        <textarea class="form-control" asp-for="Description" placeholder="Açıklama giriniz.." rows="4"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary cancel">Kapat</button>
                <button type="button" class="btn btn-primary save">Kaydet</button>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $(".cancel").click(function() {
            $(".modal").hide("slow");
        });
        $("#brandSelect").change(function() {
            $("#carModel option").each(function() {
                $(this).remove();
            });
            var id = $(this).val();
            var url = '@Url.Action("GetCarModelsByBrand","Car")';
            $.get(url, { brandId: id }).done(function(data) {
                var stringifyData = JSON.stringify(data); // "key":"data"
                var jsonData = jQuery.parseJSON(stringifyData); //jsObject
                console.log(jsonData);
                if (jsonData.isError === true) {
                    $("#carModel").append(`<option>${jsonData.message}</option>`);
                }
                else {
                    for (var carModel of jsonData) {
                        $("#carModel").append(`<option value="${carModel.id}">${carModel.name}</option>`);
                    }
                }
            });
        });

        $("#addBrand").click(function() {
            const url = '@Url.Action("Add","Brand")';
            const modalDiv = $("#modal");
            $.get(url).done(function(data) {
                modalDiv.html(data);
                modalDiv.find(".modal").show('slow');
            });
        });

        $(".save").click(function() {
            const form = $("#form-update");
            const actionUrl = form.attr("action");
            const dataToSend = form.serialize();
            $.post(actionUrl, dataToSend).done(function(data) {
                var stringifyData = JSON.stringify(data); // "key":"data"
                var jsonData = jQuery.parseJSON(stringifyData); //jsObject
                if (jsonData.resultStatus == "Success") {
                    Swal.fire({
                        icon: 'success',
                        title: 'Başarıyla Güncellendi',
                        text: jsonData.message
                    }).then((result) => {
                        if (result.isConfirmed) {
                            location.reload(true);
                        }
                    });
                } else {
                    Swal.fire({
                        icon: 'error',
                        title: 'Güncellendi Başarısız',
                        text: jsonData.message
                    });
                }
            });
        });
    });
</script>