WebUI/ViewComponents/NavbarViewComponent.cs
using Entity.Concrete;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;
using WebUI.Models;

namespace WebUI.ViewComponents
{
    public class NavbarViewComponent : ViewComponent
    {
        private readonly UserManager<User> _userManager;

        public NavbarViewComponent(UserManager<User> userManager)
        {
            _userManager = userManager;
        }

        public ViewViewComponentResult Invoke()
        {
            var user = _userManager.GetUserAsync(HttpContext.User).Result;
            return View(new NavbarModel
            {
                User = user
            });
        }
    }
}

WebUI/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Rent A Car</title>
    @await Html.PartialAsync("_LayoutCssPartial")
</head>

<body class="loading-gif">

    @await Component.InvokeAsync("Navbar")
  
    @RenderBody()

    <!--Footer-->
    <div class="container">
        <footer class="py-3 my-4">
            <ul class="nav justify-content-center border-bottom pb-3 mb-3">
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Home</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Features</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Pricing</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
                <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">About</a></li>
            </ul>
            <div class="row border-bottom">
                <div class="col-lg-6">
                    <h6>İkitelli Şubesi Şubemiz:</h6>
                    <p>
                        Ay Mahallesi Duman Yıldız Sokak 1/28
                        <br />Küçükçekmece/İstanbul
                    </p>
                    <h6>Telefon Numaramız:</h6>
                    <p>0212 999 99 99</p>
                </div>
                <div class="col-lg-6" style="position:relative;">
                    <div style="position:absolute; right:10px; bottom:10px;font-size:20px;">
                        <i class="fa-brands fa-facebook me-1"></i>
                        <i class="fa-brands fa-instagram me-1"></i>
                        <i class="fa-brands fa-twitter me-1"></i>
                    </div>
                </div>
            </div>
            <p class="text-center text-muted">© 2022 Deniz Yazılım</p>
        </footer>
    </div>
    <!--End of footer-->
   
    
    @await Html.PartialAsync("_LayoutJsPartial")
    @await RenderSectionAsync("scripts", false)
</body>

</html>

WebUI/Views/Shared/_LayoutCssPartial.cshtml
@* FONTAWESOME *@
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.2/css/all.min.css" integrity="sha512-1sCRPdkRXhBV2PBLUdRb4tMg1w2YPf37qatUFeS7zlBy7jJI8Lf4VHwWfZZfpXtYSLy85pkm9GaYVYMfw5BC1A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
@*BOOTSTRAP 5.2.0*@
<link rel="stylesheet" href="~/Main/css/bootstrap/bootstrap.min.css"/>
@*ÖZEL CSS*@
<link rel="stylesheet" href="~/Main/css/deniz.css"/>
<!--adminden gelen css-->
<link href="~/Admin/css/dz-admin.css" rel="stylesheet">

WebUI/Views/Shared/_LayoutJsPartial.cshtml
@* Jquery 3.6.0 *@
<script src="~/Main/js/jquery/jquery-3.6.0.js"></script>

<script src="~/Admin/js/dz-admin.js"></script>

@* BOOTSTRAP 5.2.0 JS *@
<script src="https://cdn.jsdelivr.net/npm/@@popperjs/core@@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
<script src="~/Main/js/bootstrap/bootstrap.min.js"></script>


@* Isotope *@
<script src="https://unpkg.com/isotope-layout@3/dist/isotope.pkgd.min.js"></script>

<!-- Sweet Alert -->
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>